### ISSUE TITLE
2 Display Kanal 8

### ISSUE THREAD

**Issue by Michel83** [jp112sdl/WemosD1_HomeMatic_StatusDisplay#10]
Ich habe gestern ein zweites Display quasi in Betrieb genommen allerdings ohne taster. Das Problem ist der Kanal 8 es funktionieren alle bis auf diesen. Wenn ich jetzt den Wert beim ersten Display des Kanal 8 verändere, ändert sich die Anzeige auf beiden Displays.

Hab ich irgendwas falsch gemacht ?

**Comment by jp112sdl** [comment]
Das kann ich nur anhand der beschriebenen Symptomatik schwer beurteilen.

Evtl. versehentlich IP doppelt vergeben?
Arbeitest du mit UDP oder HTTP Steuerung?
Ist der Gerätename eindeutig?

**Comment by Michel83** [comment]
Stimmt recht wenige Informationen

Also die HTTP Steuerung Funktioniert grade getestet, es passiert nur wenn ich diese über die CCU schalte 
![status1](https://user-images.githubusercontent.com/36561525/39407651-c49d046a-4bb8-11e8-9b02-df81595a0f23.JPG)
![status2](https://user-images.githubusercontent.com/36561525/39407652-c4bbc09e-4bb8-11e8-9702-f423a43acfe7.JPG)
![unbenannts](https://user-images.githubusercontent.com/36561525/39407653-c4d61d86-4bb8-11e8-9be1-40101b7a2a34.JPG)

Es passiert auch wenn ich es direct in den Geräten bediene

**Comment by jp112sdl** [comment]
Dann kommt ja nur eins in Frage:
Du hast ja 2 Programme. Für jedes StatusDisplay eines.
In den Programmen hast du jeweils alle 16 Kanäle des CUxD Geräts drin.
Ich vermute, dass du versehentlich in Programm 2 für StatusDisplay_2 auch noch einen Kanal von StatusDisplay_1 mit hinzugefügt hast. Oder umgekehrt - in Programm 1 für StatusDisplay_1 versehentlich einen Kanal aus StatusDisplay_2

**Comment by Michel83** [comment]
Die Programme sind in Ordnung kann auch noch mal screenshots einstellen, was ich eben auch festgestellt habe das bei der Manuellen Bedienung in der CCU  der Kanal 8 bei dem zweiten Display auch nicht funktioniert. Sondern nur wenn ich den Kanal bei dem ersten Display Wechsel. Ich hatte auch grade zum test das Programm nochmal gelöscht und neu angelegt hat aber auch nichts geholfen

**Comment by jp112sdl** [comment]
Also wenn du bspw über einen Browser den Status setzt mit
`http://<ip_display_1>/set?led=8&dim=10`
dann ändert sich die Farbe auf Kanal 8 **nur von  Display 1** entsprechend dem Dimmerwert 10...19?
Und wenn du mit 
`http://<ip_display_2>/set?led=8&dim=10`
das selbe für Display 2 machst, ändert sich auch **nur auf Display 2** der Kanal 8?

**Comment by Michel83** [comment]
Jetzt habe ich grade nochmal das Programm des ersten Displays gelöscht und neu eingegeben jetzt läuft es :-/ anscheinend ist in der CCU beim kopieren des Programms von Display 1 zu 2 was schief gegangen.

Danke für den Support !!! 
Grüße

**Comment by jp112sdl** [comment]
Hehe, ja also einen Fehler im Code hatte ich auch ausgeschlossen. Es konnte nur irgendwo von der Zentralensteuerung kommen... 

Wenns jetzt geht ist ja alles gut :) 
Viel Spaß damit!

**Comment by Michel83** [comment]
Danke noch mal, ich habe auch eine weitere Version des Displays zum Einbau ohne taster gezeichnet https://www.thingiverse.com/thing:2882182

**Comment by jp112sdl** [comment]
Hab ich mit in der Wiki-Navbar aufgenommen.
https://github.com/jp112sdl/WemosD1_HomeMatic_StatusDisplay/wiki/Housing_Michel83
Danke.
