### ISSUE TITLE
Werte von CCU beim Start laden?

### ISSUE THREAD

**Issue by spaceduck518** [jp112sdl/WemosD1_HomeMatic_StatusDisplay#11]
wie funktioniert das laden der aktuellen Werte aus der CCU? Das aktivieren der Option bewirkt kein holen der Werte beim Start des Displays. IP ist korrekt.

**Comment by jp112sdl** [comment]
Der Gerätename muss identisch sein mit dem Namen des CUxD Gerätes, das die Dimmerkanäle hat.
Angenommen du trägst als Gerätenamen **StatusDisplay1** ein, dann muss das CUxD Gerät auch so heißen.
<img width="933" alt="bildschirmfoto 2018-07-10 um 18 30 14" src="https://user-images.githubusercontent.com/18190139/42523928-6724a744-846f-11e8-8bc4-ad4e2b16432c.png">

Beim Starten wird die Adresse des CUxD-Geräts mit dem Gerätenamen des Statusdisplays gesucht und anschließend werden die Werte der einzelnen Kanäle abgefragt.

**Comment by spaceduck518** [comment]
Beide Namen sind identisch, das hatte ich bereits überprüft. Gibt es sonst noch Einstellungen in der CCU oder im CuxD die hier greifen könnten?

**Comment by spaceduck518** [comment]
Habe gerade mal den Namen auf beiden Seiten von "StatusDisplay" auf "StatusDisplay1" geändert - funktioniert! Nur "StatusDisplay" ohne Nummer funktioniert nicht. Kannst Du das evtl. bei Dir mal testen / reproduzieren?

**Comment by jp112sdl** [comment]
Hmm... kann ich auf die Schnelle nicht testen.

Hast du den Namen "StatusDisplay" an anderer Stelle verwendet? Eine Systemvariable so benannt?

**Comment by spaceduck518** [comment]
Nein, der Name existiert nicht doppelt, hatte ich ebenfalls schon geprüft. Aber ich kann mit dem workaround leben, kein Problem! 

Jan

**Comment by jp112sdl** [comment]
Ok, dann belassen wir es dabei?
Anderenfalls könntest du auch mal die seriellen Debugmeldungen am PC loggen, dann würden wir wahrscheinlich mehr sehen, weshalb es nicht klappt.

**Comment by spaceduck518** [comment]
Ja, wir lassen es so. Ich werde bei Gelegenheit mal via rs232 schauen was da passiert und melde mich dann nochmal.

Danke!
