### ISSUE TITLE
Farbe wechseln, nur eine LED möglich?

### ISSUE THREAD

**Issue by MathiasJZ** [jp112sdl/WemosD1_HomeMatic_StatusDisplay#12]
Ich möchte mir so ein Status-Display in der Nähe des Balkonfensters aufhängen.
Aber es soll nur eine LED haben, die von grün auf rot wechselt.
Das ganze soll als "Status Display" für meinen "Einbruchmelder" dienen, wenn scharf geschaltet wurde.
D.h. wenn die Lampe grün leuchtet, darf die Türe geöffnet werden, wenn rot, dann nicht.
Leider gibt es wohl keine Möglichkeit, Fragen zu stellen. Im homematic-forum habe ich diesbezüglich nichts gefunden.
Ein echtes 16-Kanal-Statusdisplay kommt für mich nicht in Frage. ich habe die Visualisierung des Hauses schon per IObroker und Wandtablet umgesetzt.
Gruß,
Mathias

**Comment by jp112sdl** [comment]
Hallo,
im Homematic Forum gibt es eine Kategorie [Hardwareentwicklung und Selbstbau von Aktoren und Sensoren](https://homematic-forum.de/forum/viewforum.php?f=76), in der du deine Frage zum Beispiel stellen könntest.

So ganz genau weiß ich auch nicht, wie ich dir hier an dieser Stelle weiterhelfen kann.

Grundsätzlich spricht nichts dagegen, an dieses Projekt hier nur eine WS2812B anzuschließen. Es müssen nicht alle 16 bestückt werden.

Andererseits ist wohl etwas überdimensioniert. 
Bei einer einfachen Rot-/Grün-LED reicht wohl [ESPEasy](https://www.letscontrolit.com/wiki/index.php/Main_Page). Die haben auch ein [Forum](https://www.letscontrolit.com/forum/).

VG,
Jérôme

**Comment by MathiasJZ** [comment]
Dankeschön für die Antwort.
Da werde ich mich gleich drum kümmern

Gruß
Mathias

Am 18. September 2018 08:21:41 schrieb Jérôme <notifications@github.com>:
