### ISSUE TITLE
Script schickt keine Daten an WEMOSD1

### ISSUE THREAD

**Issue by old-rotsch** [jp112sdl/WemosD1_HomeMatic_StatusDisplay#13]
LED Einstellungen werden beim WEMOS Boot von CCU3 übernommen.
LED ansteuern über HTTP funktioniert.
--
Nur bei Änderungen auf der Homematic kommt im WEMOS Serial Log nichts an.
CUxD Syslog:
May 18 11:32:48 ccu3-webui local0.err ReGaHss: ERROR: ScriptRuntimeError: 
```string displayIP = "192.168.100.210"; 
string channel = dom.GetObject(((dom.GetObject("22902")).Channel())).Name(); 
real r = dom.GetObject("22902").Value();  
integer val = (r * 10).ToInteger(); 
integer ledNum = channel.StrValueByIndex(":", 1).ToInteger();  
dom.GetObject("CUxD.CUX4000003:1.CMD_EXEC").State ("/usr/local/addons/cuxd/curl -s -k -d led="#ledNum#" -d dim="#val#" http://"#displayIP#"/set"); 
```
 [ExecError():iseESPexec.cpp:1288

**Comment by jp112sdl** [comment]
Wie sieht denn das vollständige Skript aus?
Ich sehe hier nirgends die `displayIP`

**Comment by old-rotsch** [comment]
Du bist echt schnell, DANKE
---- hier das komplette Script ---
string displayIP = "192.168.100.210";
string channel = dom.GetObject(((dom.GetObject("$src$")).Channel())).Name();
real r = dom.GetObject("$src$").Value();

integer val = (r * 10).ToInteger();
integer ledNum = channel.StrValueByIndex(":", 1).ToInteger();

dom.GetObject("CUxD.CUX4000003:1.CMD_EXEC").State ("/usr/local/addons/cuxd/curl -s -k -d led="#ledNum#" -d dim="#val#" http://"#displayIP#"/set");
---

**Comment by jp112sdl** [comment]
Du gibst das falsche CUxD Gerät im Skript an.
Das CUX4000003 ist das mit den Dimmerkanälen.
Das CUxD Gerät für den Exec Aufruf muss mit 28 beginnen.
https://github.com/jp112sdl/WemosD1_HomeMatic_StatusDisplay/wiki/Homematic

**Comment by old-rotsch** [comment]
Kaum macht man es richtig funktioniert es.
Das mit dem CUX28... habe ich echt nicht gesehen / Sorry
DANKE DIR

**Comment by jp112sdl** [comment]
Prima!
