### ISSUE TITLE
Taster

### ISSUE THREAD

**Issue by Michel83** [jp112sdl/WemosD1_HomeMatic_StatusDisplay#7]
Hi,

ich hätte noch ein kleines Problem wo ich nicht weiter komme.
Es geht um die Taster es ist jetzt so das die Werte bei allen unterschiedlich sind allerdings werden sie von dem Wemos nicht erkannt er sagt immer bei jedem taster 1024 erkannt.

Hier ein paar Bilder wenn ich am A0 des Wemos mit dem Multimeter messe, was ich festgestellt habe das es ein moment dauert bis der Multimeter den Wert anzeigt.

![20180330_121448](https://user-images.githubusercontent.com/36561525/38134886-a7f5f9c8-3404-11e8-9e7b-2e1154ff62fd.jpg)
![20180330_121452](https://user-images.githubusercontent.com/36561525/38134887-a8125488-3404-11e8-8881-e40ab1bf0e78.jpg)
![20180330_121458](https://user-images.githubusercontent.com/36561525/38134888-a82e019c-3404-11e8-9d5b-92bb50298ff9.jpg)
![20180330_121500](https://user-images.githubusercontent.com/36561525/38134889-a84764c0-3404-11e8-8a18-e3c097fe6903.jpg)
![20180330_121503](https://user-images.githubusercontent.com/36561525/38134890-a861a3a8-3404-11e8-9a57-c902da7be801.jpg)
![20180330_121508](https://user-images.githubusercontent.com/36561525/38134891-a87faba0-3404-11e8-8f50-273d6ddaf693.jpg)
![20180330_121514](https://user-images.githubusercontent.com/36561525/38134892-a89a4640-3404-11e8-9ca2-52baf1fb6b8e.jpg)

**Comment by jp112sdl** [comment]
Schließ den + mal bitte statt an 5V an den **3.3V** Pin des Wemos. Ich glaub das ist in meinem Schaltplan falsch.

**Comment by Michel83** [comment]
Super danke das war es, läuft :-)

**Comment by jp112sdl** [comment]
Danke für den Hinweis. Habs im Schaltplan jetzt auch geändert.

**Comment by Michel83** [comment]
Kein Problem, echt super das Teil. 

Die LED's sind noch ein wenig Hell :-)


![20180330_191534](https://user-images.githubusercontent.com/36561525/38146630-161d508c-344f-11e8-8b03-925e1052b1b9.jpg)

**Comment by jp112sdl** [comment]
> Die LED's sind noch ein wenig Hell

Das kannst du ja beliebig einstellen :)
