### ISSUE TITLE
Display friert ein

### ISSUE THREAD

**Issue by Michel83** [jp112sdl/WemosD1_HomeMatic_StatusDisplay#8]
Hi,

ich muss leider nochmal nerven. Habe noch das Problem das der Wemos hin und wieder nicht mehr erreichbar ist. Hatte dies auch schon bei meiner ersten Bastel version, dachte es läge aber an meinem Wemos weil eben Bastel.

Aber mein jetziger macht das gleiche, es ist dann so das auch die LED´s nicht mehr aktualisiert werden erst wenn ich am Display irgendeine taste drücke ist es so als ob der Wemos neu startet also die Blinkreinfolge der LED´s und danach alles wieder in Ordnung.

Gruß
Mike

**Comment by jp112sdl** [comment]
Hast du den Code selbst kompiliert oder die .bin geflasht?

**Comment by Michel83** [comment]
Die .bin geflasht wie in der Anleitung

**Comment by jp112sdl** [comment]
Ich vermute, das Problem hängt mit esp8266/Arduino#2330 zusammen.

Teste bitte mal diese hier:
[WemosD1_HomeMatic_StatusDisplay.ino.d1_mini.bin.zip](https://github.com/jp112sdl/WemosD1_HomeMatic_StatusDisplay/files/1867526/WemosD1_HomeMatic_StatusDisplay.ino.d1_mini.bin.zip)

**Comment by Michel83** [comment]
Ich teste

**Comment by Michel83** [comment]
Bis jetzt ist noch alles gut, ist das `WiFi.setSleepMode(WIFI_NONE_SLEEP);` die Änderung in dem WLAN gewesen ?
Weil ich habe noch einen Wemos als ir remote der die gleichen Bauchweh hat dann würde ich das da auch mal versuchen

**Comment by jp112sdl** [comment]
Hab die Änderungen gepusht, damit du nachschauen kannst

**Comment by Michel83** [comment]
Ich denke es läuft seit dem keine Einfrierer mehr, danke für die Anpassung.
Ich glaub bis ich da alles verstehe dauert noch ein Moment :-)

Gruß
Mike

**Comment by jp112sdl** [comment]
Perfekt 👍 
Dann viel Spaß damit - ich mach hier zu :)
