### ISSUE TITLE
WiFi Ändern geht nicht bzw. wird ignoriert 

### ISSUE THREAD

**Issue by mikes-techzone** [jp112sdl/WemosD1_HomeMatic_StatusDisplay#9]
Hallo,

ich möchte bei dem Display das WiFi ändern leider nutzt der Wemos immer das alte egal ich wie oft ich das ändere über AP Modus. Das selbe Problem habe ich mit einem (nicht allen) Sonoff POW.

gibt es irgend einen weg ohne komplettes neues flashen ?

Danke im Voraus & Gruss

Michael

**Comment by jp112sdl** [comment]
Nein, die Wifi Zugangsdaten liegen in einem anderen Speicherbereich, der beim Flashen nicht überschrieben wird. Ein Neuflashen würde also auch nicht die Wifi Daten überschreiben.

Evtl. ist ein Sonderzeichen im Passwort, das bei der Übergabe im HTTP-Get Probleme macht... Die Zugangsdaten werden erst dann gespeichert, wenn beim Speichern auch eine Verbindung zum WLAN mit den eingegebenen Daten hergestellt werden kann. Klappt dies nicht, bleiben die alten erhalten.

**Comment by jp112sdl** [comment]
Es könnte jedoch auch mit einem Bug im Wifi Stack selbst zusammenhängen...
Hab da grad was gefunden. esp8266/arduino#4476

**Comment by mikes-techzone** [comment]
Okay dann macht flashen keinen sinn.
Zu 

> Evtl. ist ein Sonderzeichen im Passwort, das bei der Übergabe im HTTP-Get Probleme macht... <

 im neuen WLAN ist das Passwort eine reine Buchstaben Kombination.

**Comment by jp112sdl** [comment]
Kannst du bitte mal seriell die Debugausgaben mitloggen? (115200 Baud)

**Comment by mikes-techzone** [comment]
Hallo ich musste wohl das andere WiFi komplett ausschalten sonst hat er sich immer wieder mit dem alten verbunden. Nachdem das alte aus war hat sich das display mit dem neuen WiFi verbunden.

Mit dem Sonoff pow funktioniert das leider nicht weil die AP Konfiguration Seite nicht geladen werden kann.

ich hab den Sonoff komplett neu geflasht dann hat es funktioniert
